### ISSUE TITLE
Extracting average values

### ISSUE THREAD

**Issue by jacobdale211** [jacobdale211/rasterbird#13]
I tried two methods to mask the bird ranges:

Taking the original bird range `.shp` file on the cumulative `stars` object 
```
brange <- sf::st_read("data/data-raw/birdlife/birds_multistress/Bylot_non_breeding_range.shp")
snowgoose <- brange[25,1]
cumul_new<- cumul[snowgoose]
```
As well as the bird grid, trying to read it in as a `stars` 
```
snowgoose <-brange[25,1]
snowgoose <- stars::read_stars("data/data-format/bird-grid/bird-grid_Snow_Goose.tif")
cumul_new <-cumul[snowgoose]
```
Previously, the first method worked for the American Golden Plover. 

Additionally, for the Red Knot I use `cumul_crop` instead of `cumul` to adjust for the different subspecies range.

In the loop, the Red knot is `i=9` and the snow goose is `i=11`. In the `.shp` file, the Red Knot is `[18,1]` and the snow goose is `[25,1]`.

**Comment by jacobdale211** [comment]
All of this can be found on `07-cumulative_exposure.R`

**Comment by david-beauchesne** [comment]
Add this to the beginning of your script:

```r
  on.exit(sf::sf_use_s2(TRUE), add = TRUE)
  sf::sf_use_s2(FALSE)
```
